### ISSUE TITLE
NEED THE NEWEST VERSION FOR SMAPI MOBILE

### ISSUE THREAD

**Issue by ferinnakya** [ZaneYork/SMAPI-Android-Installer#151]
all mod cannot load because it needs new version of smapi
![Screenshot_20210925-014605](https://user-images.githubusercontent.com/90467870/134726524-4d0e51f5-b79a-4475-b80b-5cf85a64025b.jpg)
![Screenshot_20210925-014614](https://user-images.githubusercontent.com/90467870/134726547-de92befe-6b1c-48c9-9871-8f223dad77b6.jpg)
![Screenshot_20210925-014552](https://user-images.githubusercontent.com/90467870/134726567-6fb2e37a-1d6b-4aa1-a681-ea76a164d749.jpg)

**Comment by lividhen** [comment]
First, all caps makes you seem like a very intense and can at times make you seem rude 😅.
Second, the android version of the game is on an older version of Stardew Valley. Smapi cant be updated to the newest version because that would require the newest version of the game. If you scroll down on nexus mods you can find the older versions of mods that were made for the current Smapi release that is on android. It might take some trial and error unless the mod author decided to mark them.

**Comment by ZaneYork** [comment]
see #141
