### ISSUE TITLE
what happened with the smapi 1.5 update on android?

### ISSUE THREAD

**Issue by GonzaUwU** [ZaneYork/SMAPI-Android-Installer#275]
@ZaneYork He closed the comments but I was patiently waiting for everything, I want to know how the update is going, it's been 2+ weeks since he gave an answer, he said he would be out before March but nothing yet :(

**Comment by Emof4g** [comment]
It's March so maybe just a few more days :)

**Comment by GonzaUwU** [comment]
> It's Just an estimated time. There's no Guarantee that it will be out before march.
> 
> Maybe He's busy in real life. I'm sure he's doing his best . Just be patient play the vanilla game for now. SMAPI for mobile will come out eventually.

I never said that I had no life, I'm not rushing it, I just want to know how the update is going, I only respect the lives of others, it's just concerns

**Comment by Latelle22** [comment]
zaneyork don't have the obligation to let us know about his progress. he could even drop the update without saying anything to us and that would be fine. if you want mods play 1.4 else wait and don't post nonsense threads.

**Comment by Wonder871** [comment]
Yep

**Comment by GonzaUwU** [comment]
> zaneyork don't have the obligation to let us know about his progress. he could even drop the update without saying anything to us and that would be fine. if you want mods play 1.4 else wait and don't post nonsense threads.

You don't tell me what I can do, it's my life and if I want I do what I want, with good reason everyone is disappointed in stardew valley and smapi, stardew valley android took 2+ years for 1.5
And smapi is going the same way so don't mess around as there are reasons to ask and be angry >:(

**Comment by Lynxat** [comment]
@GonzaUwU "with good reason everyone is disappointed in stardew valley and smapi". First of all, just be happy that Stardew got android port, and also SMAPI for android, it is very hard to mod and stuffs on android. How many games do you see on android that has a ton of mods like PC? I am sure you are the only one who is mostly disappointed with current state of things. 
So here is a very bright idea for not a very bright person like you, why not learn coding and modding and  make your own SMAPI, lets see if you can finish in a week, I just hope it wont take like 2+ years, or many people including Zane will be disappointed. 
So don't mess around, there are reasons to be very angry towards you too because people like you are the reason Zane closed down the main discussion thread. So now even people like us who just wait for little tiny bits of progress here and there won't get anything anymore. 
So dude, get a life, or buy a PC, or maybe go financially support Zane so he can 100% focus on this SMAPI stuffs. But if you cant afford any of those, shut the hell up and blame yourself for making things hard for everyone else. Don't forget that pretty much everyone is tired of seeing your name coming up here and there everywhere. Just because you are sitting beside a screen doesn't mean you can just act high and mighty. Think twice before you post your nonsense stuffs next time, you are getting too annoying.

**Comment by Bufftats** [comment]
@GonzaUwU Game development is tedious, especially when having to port features from PC to mobile. Learned that myself after porting my own games to play on my phone, and finding that I encountered lag that I didn't encounter in-engine. Optimization of assets for mobile devices takes time; as I said before, it's a tedious process. The same applies for software that targets mobile devices also.

Just wait patiently (it sucks, I know). In the meantime, if you wanted to play SV with modifications, you can just manually edit your save file from your phone. Just use a file explorer to open the directory of your Stardew Valley save and open it in a text editing application on your phone. I use QuickEdit to open my saves as that's when I get the less lag (due to a large filesize).

**Comment by Type21Yamashiro** [comment]
> > zaneyork don't have the obligation to let us know about his progress. he could even drop the update without saying anything to us and that would be fine. if you want mods play 1.4 else wait and don't post nonsense threads.
> 
> You don't tell me what I can do, it's my life and if I want I do what I want, with good reason everyone is disappointed in stardew valley and smapi, stardew valley android took 2+ years for 1.5 And smapi is going the same way so don't mess around as there are reasons to ask and be angry >:(


the reason 1.5 took 2 year bc of the published team
even ape himself talk about it and just work on the whole update by himself

also the progress of smapi m1.5 still working fine we will maybe get it and later this month or have to wait another month for it (we just lost the progress due to some impatient bastard just spicy of the whole chat in #246)

**Comment by lividhen** [comment]
Collaborators can still give updates in that issue.

**Comment by emokaos** [comment]
> @GonzaUwU "with good reason everyone is disappointed in stardew valley and smapi". First of all, just be happy that Stardew got android port, and also SMAPI for android, it is very hard to mod and stuffs on android. How many games do you see on android that has a ton of mods like PC? I am sure you are the only one who is mostly disappointed with current state of things. So here is a very bright idea for not a very bright person like you, why not learn coding and modding and make your own SMAPI, lets see if you can finish in a week, I just hope it wont take like 2+ years, or many people including Zane will be disappointed. So don't mess around, there are reasons to be very angry towards you too because people like you are the reason Zane closed down the main discussion thread. So now even people like us who just wait for little tiny bits of progress here and there won't get anything anymore. So dude, get a life, or buy a PC, or maybe go financially support Zane so he can 100% focus on this SMAPI stuffs. But if you cant afford any of those, shut the hell up and blame yourself for making things hard for everyone else. Don't forget that pretty much everyone is tired of seeing your name coming up here and there everywhere. Just because you are sitting beside a screen doesn't mean you can just act high and mighty. Think twice before you post your nonsense stuffs next time, you are getting too annoying.

Nobody needs to "just be happy" about anything. The only ones throwing a fit are the toxic positivity people (you) misunderstanding genuine questions and concerns just so you can spread a bs narrative that does nothing but harm people.

**Comment by argoplus** [comment]
ya no abran más casos, esto no es Twitter.
