### ISSUE TITLE
What is the progress at the moment

### ISSUE THREAD

**Issue by FansaiKudosai** [ZaneYork/SMAPI-Android-Installer#292]
April is coming soon, and the channel where the update progress was published was closed due to some "too heated" people. ZaneYork, how far have you progressed? We are ready to wait as long as it takes, but this is already unbearable.

**Comment by ArcaneDescent** [comment]
he will update us when he's ready to

**Comment by Caeljin** [comment]
I hope the mods in the nexus site did not changed THAT much and still be compatible in the android version (cannot play without the automate) 😅

**Comment by Chezst** [comment]
"Just want to add - the developer (ZaneYork) did *not* say it'll be out by March. That was an early tentative hopeful estimate,  not an actual ETA and definitely not a date for release."

Just a comment I got from the SMAPI reddit forum. If someone can confirm, then even better. But do not get you hopes up on getting it today xD who knos, maybe not even April. We just have to wait patiently, since it's basically a favor per se.

Ps.: somewhere to donate to Zaneyork... does anybody know?

**Comment by Chezst** [comment]
> I hope the mods in the nexus site did not changed THAT much and still be compatible with the android version (cannot play without the automate) 😅

I feel ya... I can't wait for the "awake 24 hours" and "no fishing mini game" mods 😩 it's surprisingly annoying to play without them.

**Comment by haeseull** [comment]
honestly
There's a date that Jane said...
If it doesn't come out within that date
Even if it's completed in a few months, I just want you to tell me
There's gonna be a few pushy haters, but 99% of them can wait comfortably
And, um... I don't understand how you sarcastically say "learn coding" and "you didn't pay" to people who politely ask for dates, not to be mean to Jane...
You can ask if you don't give money to Jane (of course it would be better if you donated it lol) because it's way past the deadline that Jane said?
We're all people who want to enjoy smapi, so let's talk in a round way
It could be awkward because I used a translator Lol

**Comment by lividhen** [comment]
> honestly
> There's a date that Jane said...
> If it doesn't come out within that date
> Even if it's completed in a few months, I just want you to tell me
> There's gonna be a few pushy haters, but 99% of them can wait comfortably
> And, um... I don't understand how you sarcastically say "learn coding" and "you didn't pay" to people who politely ask for dates, not to be mean to Jane...
> You can ask if you don't give money to Jane (of course it would be better if you donated it lol) because it's way past the deadline that Jane said?
> We're all people who want to enjoy smapi, so let's talk in a round way
> It could be awkward because I used a translator Lol

 😂 Zane became Jane. That's amusing.
Anyway, there is a weird thing with the whole open source development thing. They're not getting paid for it, it's on their own time. I think asking for an Eta is very reasonable. But over the internet it is very hard to convey tone. It's hard to tell who is kindly asking when it will be done and who is demanding a release date. Since it is ambiguous people tend to lean hard one direction or the other and respond accordingly.

**Comment by Samantha802** [comment]
> honestly There's a date that Jane said... If it doesn't come out within that date Even if it's completed in a few months, I just want you to tell me There's gonna be a few pushy haters, but 99% of them can wait comfortably And, um... I don't understand how you sarcastically say "learn coding" and "you didn't pay" to people who politely ask for dates, not to be mean to Jane... You can ask if you don't give money to Jane (of course it would be better if you donated it lol) because it's way past the deadline that Jane said? We're all people who want to enjoy smapi, so let's talk in a round way It could be awkward because I used a translator Lol

Zane did not give a deadline. He hoped to have it done by March. That has not happened. I am sure Zane is busy trying to get the update out and will update when possible.

**Comment by Chezst** [comment]
> > honestly
> > There's a date that Jane said...
> > If it doesn't come out within that date
> > Even if it's completed in a few months, I just want you to tell me
> > There's gonna be a few pushy haters, but 99% of them can wait comfortably
> > And, um... I don't understand how you sarcastically say "learn coding" and "you didn't pay" to people who politely ask for dates, not to be mean to Jane...
> > You can ask if you don't give money to Jane (of course it would be better if you donated it lol) because it's way past the deadline that Jane said?
> > We're all people who want to enjoy smapi, so let's talk in a round way
> > It could be awkward because I used a translator Lol
> 
> 😂 Zane became Jane. That's amusing. Anyway, there is a weird thing with the whole open source development thing. They're not getting paid for it, it's on their own time. But I think asking for an Eta is very reasonable. They don't have to answer though. The problem is that over the internet it is very hard to convey tone. It's hard to tell who is kindly asking when it will be done and who is demanding a release date. Since it is ambiguous people tend to lean hard one direction or the other and respond accordingly.

That is sooo true!
