### ISSUE TITLE
Hurry up and make it

### ISSUE THREAD

**Issue by CHINAisgod** [ZaneYork/SMAPI-Android-Installer#293]
It's coming out in March. You're making it so slow.How long do I have to wait.I can't wait any longer, so give me the finished product.

**Comment by Emof4g** [comment]
If you really want it so bad how about you learn programming and do it by yourself

**Comment by batatafalha** [comment]
Zane also has other things to do. You should be grateful he's doing this, because he could drop the project if he wanted to and just not update.

**Comment by KawaiFoxHappyClaws76** [comment]
@CHINAisgod Go Pray to Mao to give it Dipsh*t. Dont Bother The Zane For His work. 🤬🤬🤬

**Comment by Rioshinki** [comment]
@CHINAisgod Dude just be patient. Things like this take time and Zane is just trying his best to make this for all of us. I get that it can be frustrating because your anxious, but give them the time that they need to update it please. Zane has his own life and can't sit down all day to work on this. Like a lot of other people said, if you want it updated so bad then just do it yourself.

**Comment by AbdulQudoss** [comment]
> It's coming out in March. You're making it so slow.How long do I have to wait.I can't wait any longer, so give me the finished product.

Bro you are acting like you paying him to make the app like let the man be he has a life let him enjoy it and go outside ffs line things take time

**Comment by lividhen** [comment]
_Outside?_ Who ever heard of such a thing?!
/s

**Comment by FarrelF** [comment]
He doesn't yet update this project due to have other things to do by him. So, if you want it so bad, there is a solution for you: (Choose one)

- Compiled it by yourself, maybe you can use Android Studio to compile it or wait until someone compiles it for you, then test it by yourself. Not working? Then you can learn some programming language (in this case, you need to learn Java and maybe C# since regular SMAPI using it) and fix it by yourself, then make a proper pull request to contribute this project or wait until someone do it for you.
- Pay to the project owner if they can provide a compiled version of this app, you need to ask it first. Alternatively, donate your money to this project as creating any software/app need funds, perhaps that will speed up the development process.
- Use your Desktop PC or Laptop, install the Stardew Valley, install a [reguler SMAPI](https://github.com/Pathoschild/SMAPI) and any mods you want, copy the save files to PC if any, then play it there. You don't have one? Then you can rent, borrow ones of it from someone, build a PC or just buy one of it.

	Fortunately, Stardew Valley doesn't require high-end hardware to be playable, so you can use a cheap/affordable/low-end PC or Laptop with 8 GB of RAM (4x2 GB Dual-channel if you can) and a 256 GB SSD which is recommended if you're using Windows 10 and you want to use a lot of mods and/or using mods that need a bit more your PC/Laptop resources (it can be lower than that if you're using Linux or below of Windows 10, e.g. Windows 7 or Windows 8.1, or you just don't want to use a lot of mods, etc).

Hopefully, one of my solutions above can help you to solve your problem instead of just whining to someone :)

**Comment by Roshan9k** [comment]
These impatient kids had forgotten how long it took for the game to update. Smapi won't just appear prepared out of nowhere, so don't expect it to. It takes time to complete this process. Give the man all the time he requires.

**Comment by RadioGlass** [comment]
> It's coming out in March. You're making it so slow.How long do I have to wait.I can't wait any longer, so give me the finished product.

You really made an account just to be a butthole. You're not speeding up the process by commenting this, if anything your making it more difficult. It's done when its done, if not start learning how to make this yourself or play on another platform.

**Comment by xaronax2** [comment]
I'll donate $10 if you delay it 6 months just for that guy.

**Comment by Rioshinki** [comment]
> I'll donate $10 if you delay it 6 months just for that guy.

A lot of people would, I probably would too.
