### ISSUE TITLE
Why does it take so long to make one?

### ISSUE THREAD

**Issue by CHINAisgod** [ZaneYork/SMAPI-Android-Installer#294]
If you're a developer, make it quickly. And don't care who else I ask.

**Comment by Type21Yamashiro** [comment]
> If you're a developer, make it quickly. And don't care who else I ask.

another impatient bastard...

**Comment by argoplus** [comment]
que tristeza ver gente tan mal educada. sinceramente si espero con ansias que salga pero jamás tendría ese comportamiento... zane deberías abandonar el proyecto, esta gente no merece que gastes tu valioso tiempo.

**Comment by Rioshinki** [comment]
You aren't paying him to make this. He is it as his own project. You don't own anything here. You have the guts to not only say something once but twice. I seriously hope he just drops it because people like you don't give a **** about Zane. Make it yourself because apparently to you it shouldn't be hard at all.

**Comment by Emof4g** [comment]
I wish u shit and find no paper toilet left
