### ISSUE TITLE
Someone else or is it just me? 

### ISSUE THREAD

**Issue by SAMOELBR** [ZaneYork/SMAPI-Android-Installer#635]
My smapi won't open, it just closes by itself 
https://github.com/ZaneYork/SMAPI-Android-Installer/assets/122221741/95246b91-7a6a-42bf-a3bb-dfdb88be50d1

**Comment by 3Negativ3** [comment]
Check out the previous issues #614 Apparently smapi is not compatible with the latest version of stardew valley 1.5.6.52. Honestly I'm not sure because mine works with no problem.
![Screenshot_20231203-172223](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/127725988/5c7e2510-1e0c-40d8-bd5c-63adb3a23954)
![Screenshot_20231203-172302](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/127725988/9ef74e74-e294-48e9-90e0-5658bfae1afb)

**Comment by 3Negativ3** [comment]
Have you tried deleting StradewValley and Smapi internal folders?

**Comment by SAMOELBR** [comment]
Yes I've done everything and mine a bit and still still have the same error/problem

**Comment by SAMOELBR** [comment]
I solved the problem, just restart the phone
